columns:
  Elevation: int64
  Aspect: int64
  Slope: int64
  Horizontal_Distance_To_Hydrology: int64
  Vertical_Distance_To_Hydrology: int64
  Horizontal_Distance_To_Roadways: int64
  Hillshade_9am: int64
  Hillshade_Noon: int64
  Hillshade_3pm: int64
  Horizontal_Distance_To_Fire_Points: int64
  Wilderness_Area1: int64
  Wilderness_Area2: int64
  Wilderness_Area3: int64
  Wilderness_Area4: int64
  Soil_Type1: int64
  Soil_Type2: int64
  Soil_Type3: int64
  Soil_Type4: int64
  Soil_Type5: int64
  Soil_Type6: int64
  Soil_Type7: int64
  Soil_Type8: int64
  Soil_Type9: int64
  Soil_Type10: int64
  Soil_Type11: int64
  Soil_Type12: int64
  Soil_Type13: int64
  Soil_Type14: int64
  Soil_Type15: int64
  Soil_Type16: int64
  Soil_Type17: int64
  Soil_Type18: int64
  Soil_Type19: int64
  Soil_Type20: int64
  Soil_Type21: int64
  Soil_Type22: int64
  Soil_Type23: int64
  Soil_Type24: int64
  Soil_Type25: int64
  Soil_Type26: int64
  Soil_Type27: int64
  Soil_Type28: int64
  Soil_Type29: int64
  Soil_Type30: int64
  Soil_Type31: int64
  Soil_Type32: int64
  Soil_Type33: int64
  Soil_Type34: int64
  Soil_Type35: int64
  Soil_Type36: int64
  Soil_Type37: int64
  Soil_Type38: int64
  Soil_Type39: int64
  Soil_Type40: int64
  Cover_Type: int64

numerical_columns:
  - Elevation
  - Aspect
  - Slope
  - Horizontal_Distance_To_Hydrology
  - Vertical_Distance_To_Hydrology
  - Horizontal_Distance_To_Roadways
  - Hillshade_9am
  - Hillshade_Noon
  - Hillshade_3pm
  - Horizontal_Distance_To_Fire_Points
  - Wilderness_Area1
  - Wilderness_Area2
  - Wilderness_Area3
  - Wilderness_Area4
  - Soil_Type1
  - Soil_Type2
  - Soil_Type3
  - Soil_Type4
  - Soil_Type5
  - Soil_Type6
  - Soil_Type7
  - Soil_Type8
  - Soil_Type9
  - Soil_Type10
  - Soil_Type11
  - Soil_Type12
  - Soil_Type13
  - Soil_Type14
  - Soil_Type15
  - Soil_Type16
  - Soil_Type17
  - Soil_Type18
  - Soil_Type19
  - Soil_Type20
  - Soil_Type21
  - Soil_Type22
  - Soil_Type23
  - Soil_Type24
  - Soil_Type25
  - Soil_Type26
  - Soil_Type27
  - Soil_Type28
  - Soil_Type29
  - Soil_Type30
  - Soil_Type31
  - Soil_Type32
  - Soil_Type33
  - Soil_Type34
  - Soil_Type35
  - Soil_Type36
  - Soil_Type37
  - Soil_Type38
  - Soil_Type39
  - Soil_Type40

target_column: Cover_Type
